services:
  activemq:
    image: apache/activemq-classic
    container_name: activemq
    ports:
      - "61616:61616"  # JMS port
      - "8161:8161"    # Admin GUI
    environment:
      - ACTIVEMQ_WEB_USER=admin
      - ACTIVEMQ_WEB_PASSWORD=admin
      - ACTIVEMQ_CONNECTION_USER=user
      - ACTIVEMQ_CONNECTION_PASSWORD=password
