spring:
  application.name: SpringBootActiveMQ
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  docker:
    compose:
      lifecycle-management: start_only

jms:
  clientId: myClientId
  queueName: demo.queue
  topicName: demo.topic
  durable:
    subscription: mySubscription
