#file: noinspection SpringBootApplicationYaml
spring:
  application.name: SpringBootActiveMQ
  docker:
    compose:
      lifecycle-management: start_only

jms:
  broker:
    url: tcp://localhost:61616
    user: user
    password: password
  clientId: myClientId
  queueName: demo.queue
  topicName: demo.topic
  durable:
    subscription: mySubscription
